# Site settings
title: Bram Alferink`s Homepage
description: Personal website
baseurl: ""
url: "https://BDAlferink.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
